### PR TITLE
Create Avatar documentation for Android

### PR DESCRIPTION
**Pull request by danoc**
Credit goes to @MutatedGamer for doing all this work. I simply made the PR so that he had a branch to work off of.

### CODE REVIEW

**Comment by danoc** [comment]
This looks great to me!

@mallikapotter — Here is the page:
https://deploy-preview-371--thumbprint.netlify.com/components/avatar/android/

**Comment by danoc** [comment]
@tomgenoni — What do you think of this message I've added to the top of the page?

image

**Comment by tomgenoni** [comment]
I think that's fine. I'm not sure how other companies handle it. Do we plan to open source it?

**Comment by danoc** [comment]
> I think that's fine. I'm not sure how other companies handle it. Do we plan to open source it?

Need to officially get approval, but most Android developers I've chatted with are in favor. Main blocker is moving the components into their own codebase.

**Comment by danoc** [comment]
@MutatedGamer — This looks good to me! LMK if you're ready for it to be merged and I'll merge.

**Comment by MutatedGamer** [comment]
LGTM! Let's ship it 👍

**Pull request merged**
