### PR TITLE
Added ThumbprintUI alert banner documentation

### PR DESCRIPTION
**Pull request by Abdul-Moiz**
Added ThumbprintUI alert banner documentation 
- Mostly same as UIKit counterpart with SwiftUI example as addition.

### CODE REVIEW

**Review by danoc — APPROVED** [review]
Looks good to me. @egoens, what about you?

Here's the preview link:
https://deploy-preview-867--thumbprint.netlify.app/components/alert-banner/swiftui/

**Comment by egoens** [comment]
The scale of the images is a bit large. The image might be at 2x. We should be able to define a width of 375px to make the scale feel more appropriate.

There is also a typo on the Caution example: (ypur should be your)

image

**Comment by Abdul-Moiz** [comment]
Typo and image scale issue fixed.

**Review by egoens — APPROVED** [review]

**Comment by danoc** [comment]
Thanks for the PR! It will be live on thumbprint.design in ~5 mins.

**Comment by Abdul-Moiz** [comment]
Thank you.

**Pull request merged**
