### PR TITLE
Create Tokens for Android

### PR DESCRIPTION
**Pull request by danoc**
This creates the tokens but does not publish or document them. Those will be follow-up tasks.

This is the output:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="blue_100">#eaf6fa</color>
    <color name="blue_200">#b3ebff</color>
    <color name="blue_300">#79d2f2</color>
    <color name="blue">#009fd9</color>
    <color name="blue_500">#007fad</color>
    <color name="blue_600">#005a7a</color>
    <color name="indigo_100">#e8f1fd</color>
    <color name="indigo_200">#cce1ff</color>
    <color name="indigo_300">#96c2ff</color>
    ...
    <color name="red_600">#76012c</color>
    <color name="black_300">#676d73</color>
    <color name="black">#2f3033</color>
    <color name="gray_200">#fafafa</color>
    <color name="gray_300">#e9eced</color>
    <color name="gray">#d3d4d5</color>
    <color name="white">#ffffff</color>
    <dimen name="space_1">4dp</dimen>
    <dimen name="space_2">8dp</dimen>
    <dimen name="space_3">16dp</dimen>
    <dimen name="space_4">24dp</dimen>
    <dimen name="space_5">32dp</dimen>
    <dimen name="space_6">48dp</dimen>
</resources>
```

Adding @mallikapotter for Android related things and @tomgenoni for Thumbprint Tokens scripts.

### CODE REVIEW

**Comment by danoc** [comment]
@mallikapotter — Do you think we should prefix these with `tp_`? While unlikely, we run the risk of adding something in this codebase that silently breaks something else in the Android codebase. 

(This is similar to what we do for [our SCSS Tokens](https://unpkg.com/@thumbtack/thumbprint-tokens@8.0.2/dist/scss/_index.scss) and is [what Salesforce does](https://github.com/salesforce-ux/design-system-android/blob/master/SalesforceDesignSystem/src/main/res/values/force-base.android.color.xml).)

#### Downsides

* Token names become a longer
* There's a one-time migration cost

#### Advantages

* It's safer since name conflicts from changes in Thumbprint become be far less likely to happen.
* Developers can more easily identify which resources are "officially" part of Thumbprint.
* Auto-complete and Android studio will filter out non Thumbprint resources when a developer types `@color/tp_` or `@dimens/tp_`.

***

If we do this, I'd be happy to handle the migration in a backwards compatible way that doesn't break in-flight work.

**Comment by mallikapotter** [comment]
Couple of comments:

1. I'd personally prefer not to prefix with tp_ to avoid having to refactor our color usage in the codebase.

2. Dimens and colors should be in two separate files -> colors.xml and dimens.xml

**Comment by danoc** [comment]
>
> 1. I'm ambivalent on prefixing tp_, but we should ask in #eng-android
>

Good call. I'll do this.

>
> 2. Dimens and colors should be in two separate files -> colors.xml and dimens.xml
>

Is this a hard requirement or just standard convention? When chatting with @fkam-tt last week it seemed that it's only convention/organizational. Our tokens script (and the open-source ones available) don't support exports of multiple files, so I'd rather not add that only for Android if it's not required.

**Comment by mallikapotter** [comment]
> Is this a hard requirement or just standard convention? When chatting with @fkam-tt last week it seemed that it's only convention/organizational. Our tokens script (and the open-source ones available) don't support exports of multiple files, so I'd rather not add that only for Android if it's not required.

True, they do all get merged eventually. If Francis is ok with it, I'm fine with it.

**Comment by fkam-tt** [comment]
> > Is this a hard requirement or just standard convention? When chatting with @fkam-tt last week it seemed that it's only convention/organizational. Our tokens script (and the open-source ones available) don't support exports of multiple files, so I'd rather not add that only for Android if it's not required.
> 
> True, they do all get merged eventually. If Francis is ok with it, I'm fine with it.

Yep, the filename is technically arbitrary and since it's just generated code anyway, I'm fine with it all being in one.

**Comment by danoc** [comment]
This is the new output:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="tp_blue_100">#eaf6fa</color>
    <color name="tp_blue_200">#b3ebff</color>
    <color name="tp_blue_300">#79d2f2</color>
    <color name="tp_blue">#009fd9</color>
    <color name="tp_blue_500">#007fad</color>
    <color name="tp_blue_600">#005a7a</color>
    <color name="tp_indigo_100">#e8f1fd</color>
    <color name="tp_indigo_200">#cce1ff</color>
    <color name="tp_indigo_300">#96c2ff</color>
    <color name="tp_indigo">#5968e2</color>
    <color name="tp_indigo_500">#4f54b3</color>
    <color name="tp_indigo_600">#383c80</color>
    <color name="tp_purple_100">#f5efff</color>
    <color name="tp_purple_200">#dfccff</color>
    <color name="tp_purple_300">#d3baff</color>
    <color name="tp_purple">#a97ff0</color>
    <color name="tp_purple_500">#8a5ed6</color>
    <color name="tp_purple_600">#502095</color>
    <color name="tp_green_100">#e1fdf3</color>
    <color name="tp_green_200">#c6f7da</color>
    <color name="tp_green_300">#73e4a2</color>
    <color name="tp_green">#2db783</color>
    <color name="tp_green_500">#109e78</color>
    <color name="tp_green_600">#0f6648</color>
    <color name="tp_yellow_100">#fdf7e7</color>
    <color name="tp_yellow_200">#ffebb3</color>
    <color name="tp_yellow_300">#ffdd80</color>
    <color name="tp_yellow">#febe14</color>
    <color name="tp_yellow_500">#d48300</color>
    <color name="tp_yellow_600">#8a5500</color>
    <color name="tp_red_100">#ffeff0</color>
    <color name="tp_red_200">#ffd9d9</color>
    <color name="tp_red_300">#ffb0b0</color>
    <color name="tp_red">#ff5a5f</color>
    <color name="tp_red_500">#cc3553</color>
    <color name="tp_red_600">#76012c</color>
    <color name="tp_black_300">#676d73</color>
    <color name="tp_black">#2f3033</color>
    <color name="tp_gray_200">#fafafa</color>
    <color name="tp_gray_300">#e9eced</color>
    <color name="tp_gray">#d3d4d5</color>
    <color name="tp_white">#ffffff</color>
    <dimen name="tp_space_tp_1">4dp</dimen>
    <dimen name="tp_space_tp_2">8dp</dimen>
    <dimen name="tp_space_tp_3">16dp</dimen>
    <dimen name="tp_space_tp_4">24dp</dimen>
    <dimen name="tp_space_tp_5">32dp</dimen>
    <dimen name="tp_space_tp_6">48dp</dimen>
</resources>
```

**Comment by danoc** [comment]
This is the new output:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="tp_blue_100">#eaf6fa</color>
    <color name="tp_blue_200">#b3ebff</color>
    <color name="tp_blue_300">#79d2f2</color>
    <color name="tp_blue">#009fd9</color>
    <color name="tp_blue_500">#007fad</color>
    <color name="tp_blue_600">#005a7a</color>
    <color name="tp_indigo_100">#e8f1fd</color>
    <color name="tp_indigo_200">#cce1ff</color>
    <color name="tp_indigo_300">#96c2ff</color>
    <color name="tp_indigo">#5968e2</color>
    <color name="tp_indigo_500">#4f54b3</color>
    <color name="tp_indigo_600">#383c80</color>
    <color name="tp_purple_100">#f5efff</color>
    <color name="tp_purple_200">#dfccff</color>
    <color name="tp_purple_300">#d3baff</color>
    <color name="tp_purple">#a97ff0</color>
    <color name="tp_purple_500">#8a5ed6</color>
    <color name="tp_purple_600">#502095</color>
    <color name="tp_green_100">#e1fdf3</color>
    <color name="tp_green_200">#c6f7da</color>
    <color name="tp_green_300">#73e4a2</color>
    <color name="tp_green">#2db783</color>
    <color name="tp_green_500">#109e78</color>
    <color name="tp_green_600">#0f6648</color>
    <color name="tp_yellow_100">#fdf7e7</color>
    <color name="tp_yellow_200">#ffebb3</color>
    <color name="tp_yellow_300">#ffdd80</color>
    <color name="tp_yellow">#febe14</color>
    <color name="tp_yellow_500">#d48300</color>
    <color name="tp_yellow_600">#8a5500</color>
    <color name="tp_red_100">#ffeff0</color>
    <color name="tp_red_200">#ffd9d9</color>
    <color name="tp_red_300">#ffb0b0</color>
    <color name="tp_red">#ff5a5f</color>
    <color name="tp_red_500">#cc3553</color>
    <color name="tp_red_600">#76012c</color>
    <color name="tp_black_300">#676d73</color>
    <color name="tp_black">#2f3033</color>
    <color name="tp_gray_200">#fafafa</color>
    <color name="tp_gray_300">#e9eced</color>
    <color name="tp_gray">#d3d4d5</color>
    <color name="tp_white">#ffffff</color>
    <dimen name="tp_space_1">4dp</dimen>
    <dimen name="tp_space_2">8dp</dimen>
    <dimen name="tp_space_3">16dp</dimen>
    <dimen name="tp_space_4">24dp</dimen>
    <dimen name="tp_space_5">32dp</dimen>
    <dimen name="tp_space_6">48dp</dimen>
</resources>
```

**Comment by danoc** [comment]
@tomgenoni, @mallikapotter — I think this is good to go!

**Pull request merged**
