### PR TITLE
Added TPAvatar and TPStarRating documentation

### PR DESCRIPTION
**Pull request by tt-pkaminski**
Adding documentation for the SwiftUI versions of the `TPStarRating` and `TPAvatar`

### CODE REVIEW

**Review by danoc — APPROVED** [review]
Ty!

**Comment by tt-pkaminski** [comment]
@Abdul-Moiz @dwroth feel free to take a pass and let me know if you have any suggestions from an iOS standpoint on the documentation.

**Comment by Abdul-Moiz** [comment]
> @Abdul-Moiz @dwroth feel free to take a pass and let me know if you have any suggestions from an iOS standpoint on the documentation.

I did take a look. It's looking good. Just wondering do we need to add any documentation on custom theming/sizing? 
eg: https://thumbprint.design/components/loader-dots/swiftui/#section-custom-theme-and-size

**Review by Abdul-Moiz — APPROVED** [review]

**Comment by tt-pkaminski** [comment]
> Just wondering do we need to add any documentation on custom theming/sizing?

I did try to call that out in my examples, but if we want an explicit section to standardize the documentation, I can do that.

**Comment by Abdul-Moiz** [comment]
> I did try to call that out in my examples, but if we want an explicit section to standardize the documentation, I can do that.

I guess we are covered. I see it in the examples now.

**Pull request merged**
