### PR TITLE
Add heightAboveSmall prop to ModalDefault (#433)

### PR DESCRIPTION
**Pull request by jichan-thumbtack**

### CODE REVIEW

**Comment by jichan-thumbtack** [comment]
I added a commit to fix the bottom padding issue in Firefox and Edge

Tested on Chrome, Safari, Firefox, Edge, IE11 but please take a second look

**Comment by jichan-thumbtack** [comment]
Thanks for catching that; I think now that we have a nested `<div>` for adding padding to curtain, if the click originates from there, this check fails (https://github.com/thumbtack/thumbprint/blob/master/packages/thumbprint-react/components/ModalCurtain/index.jsx#L105)

Would it be okay to duplicate (or move) this https://github.com/thumbtack/thumbprint/blob/master/packages/thumbprint-react/components/ModalDefault/index.jsx#L59 to `curtainPadding` node? curtainPadding node is now the real `target` where the click originates from.

**Comment by danoc** [comment]
@jichan-thumbtack — It's been a while since I've worked in this file, but I think that will work!

**Comment by danoc** [comment]
Thanks for the change! Taking a look now.

**Comment by jichan-thumbtack** [comment]
I made a few tweaks to fix some issues that I saw on IE11 and Safari in the latest commit as well as some typos.
I spent literally hours attempting to fix the tall sticky footer modal on IE11 (which exists on current version as well; seems related to https://github.com/philipwalton/flexbugs/issues/216) in a trial-and-error fashion; fixing it one way for one browser breaks another browser and I thought it's too much time sink for what it's worth

**Comment by danoc** [comment]
> I made a few tweaks to fix some issues that I saw on IE11 and Safari in the latest commit as well as some typos.
> I spent literally hours attempting to fix the tall sticky footer modal on IE11 (which exists on current version as well; seems related to [philipwalton/flexbugs#216](https://github.com/philipwalton/flexbugs/issues/216)) in a trial-and-error fashion; fixing it one way for one browser breaks another browser and I thought it's too much time sink for what it's worth

Thanks for digging into it! I agree that it's probably not worth it. 👍

**Pull request merged**
